### ISSUE TITLE
Loads of worker timout errors

### ISSUE THREAD

**Issue by carkod** [canonical/jp.ubuntu.com#417]
jp.ubuntu.com workers time out a lot, try to adjust it by increasing the number of workers

Original source: https://sentry.is.canonical.com/canonical/jp-ubuntu-com/issues/2104/?query=is%3Aunresolved

**Comment by mtruj013** [comment]
Relevant meeting notes here: https://github.com/canonical/web-design-meetings/issues/70

**Comment by sowasred2012** [comment]
Related meeting notes: https://github.com/canonical/web-design-meetings/issues/70
